heat_template_version: 2013-05-23

parameters:
  image_id:
    type: string
    label: Image id
    description: Image id
    default: 2d2e5ea1-5afe-47a3-aad7-b803c4bd7ec8

resources:
  controller:
    type: OS::Nova::Server
    properties:
      name: controller
      image: { get_param: image_id }
      flavor: m1.medium
      key_name: fep
      networks:
      - network: vlan9
      # user_data:
      #   str_replace:
      #     template: {get_file: init_nodes.sh}
      #     params:
      #       $NODE: "controller"

  compute:
    type: OS::Nova::Server
    properties:
      name: compute
      image: { get_param: image_id }
      flavor: m1.medium
      key_name: fep
      networks:
      - network: vlan9
      # user_data:
      #   str_replace:
      #     template: {get_file: init_nodes.sh}
      #     params:
      #       $NODE: "compute"
